name: Sync to Gitee

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Gitee
        run: |
          git remote add gitee https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/minnmeichan/minnmeichan.git
          git config --global http.postBuffer 524288000
          git push --verbose gitee main --force
